name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release & Publish
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nikoheikkila'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint code
        run: bun run lint

      - name: Run tests
        run: bun test

      - name: Build package
        run: bun run build

      - name: Verify package contents
        run: npm pack --dry-run

      - name: Extract version info
        id: version_info
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          if [[ $VERSION == *"preview"* ]] || [[ $VERSION == *"alpha"* ]] || [[ $VERSION == *"beta"* ]] || [[ $VERSION == *"rc"* ]]; then
            echo "TAG=preview" >> $GITHUB_OUTPUT
            echo "IS_PRERELEASE=true" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
            echo "IS_PRERELEASE=false" >> $GITHUB_OUTPUT
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Publish to GitHub Packages
        run: npm publish --tag ${{ steps.version_info.outputs.TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Generate changelog
        id: changelog
        run: |
          if [ -f CHANGELOG.md ]; then
            CHANGELOG=$(awk "/^## \[?${{ steps.version_info.outputs.VERSION }}\]?/{flag=1; next} /^## \[?[0-9]/{flag=0} flag" CHANGELOG.md)
          else
            CHANGELOG="Release ${{ steps.version_info.outputs.VERSION }}"
          fi
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ## Changes
            ${{ steps.changelog.outputs.CHANGELOG }}
            
            ## Installation
            
            ```bash
            # Configure GitHub Packages registry
            echo "@nikoheikkila:registry=https://npm.pkg.github.com" >> .npmrc
            
            # Install the package
            npm install @nikoheikkila/maps@${{ steps.version_info.outputs.VERSION }}
            ```
            
            ## Verification
            
            This release was built and tested with:
            - Bun: Latest
            - Node.js: 20
            - All tests passing ✅
          draft: false
          prerelease: ${{ steps.version_info.outputs.IS_PRERELEASE }}
